import 'package:ip2location/ip2location.dart';
import 'package:test/test.dart';

void main() {
  var notSupported = 'This parameter is unavailable for selected data file. Please upgrade the data file.';
  var db26IPv4File =
      r'C:\your_folder\IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE-ADDRESSTYPE-CATEGORY-DISTRICT-ASN.BIN';
  var db26IPv6File =
      r'C:\your_folder\IPV6-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE-ADDRESSTYPE-CATEGORY-DISTRICT-ASN.BIN';
  group('Test Normal IPv4', () {
    test('Normal IPv4 US', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, 'US');
      expect(result.countryLong, 'United States of America');
      expect(result.region, 'California');
      expect(result.city, 'Mountain View');
      expect(result.isp, 'Google LLC');
      expect(result.latitude?.toStringAsFixed(6), '37.405991');
      expect(result.longitude?.toStringAsFixed(6), '-122.078514');
      expect(result.domain, 'google.com');
      expect(result.zipCode, '94043');
      expect(result.netSpeed, 'T1');
      expect(result.timeZone, '-07:00');
      expect(result.iddCode, '1');
      expect(result.areaCode, '650');
      expect(result.weatherStationCode, 'USCA0746');
      expect(result.weatherStationName, 'Mountain View');
      expect(result.mcc, '-');
      expect(result.mnc, '-');
      expect(result.mobileBrand, '-');
      expect(result.elevation, 32.0);
      expect(result.usageType, 'DCH');
      expect(result.addressType, 'A');
      expect(result.category, 'IAB19-11');
      expect(result.district, 'San Diego County');
      expect(result.asn, '15169');
      expect(result.asName, 'Google LLC');
    });
    test('Normal IPv4 MY', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('175.144.140.232');
      expect(result.ipAddress, '175.144.140.232');
      expect(result.countryShort, 'MY');
      expect(result.countryLong, 'Malaysia');
      expect(result.region, 'Pulau Pinang');
      expect(result.city, 'George Town');
      expect(result.isp, 'Telekom Malaysia Berhad');
      expect(result.latitude?.toStringAsFixed(6), '5.411460');
      expect(result.longitude?.toStringAsFixed(6), '100.335426');
      expect(result.domain, 'tm.net.my');
      expect(result.zipCode, '10300');
      expect(result.netSpeed, 'DSL');
      expect(result.timeZone, '+08:00');
      expect(result.iddCode, '60');
      expect(result.areaCode, '04');
      expect(result.weatherStationCode, 'MYXX0002');
      expect(result.weatherStationName, 'George Town');
      expect(result.mcc, '-');
      expect(result.mnc, '-');
      expect(result.mobileBrand, '-');
      expect(result.elevation, 2.0);
      expect(result.usageType, 'ISP');
      expect(result.addressType, 'U');
      expect(result.category, 'IAB19-18');
      expect(result.district, 'Daerah Timur Laut');
      expect(result.asn, '4788');
      expect(result.asName, 'Telekom Malaysia Berhad');
    });
  }, skip: 'Skipping Normal IPv4 tests first.');
  group('Test Normal IPv6', () {
    test('Normal IPv6 AU', () async {
      var ipl = IP2Location(databasePath: db26IPv6File);
      var result = await ipl.getAll('2404:6800:4001:811::200e');
      expect(result.ipAddress, '2404:6800:4001:0811:0000:0000:0000:200E');
      expect(result.countryShort, 'AU');
      expect(result.countryLong, 'Australia');
      expect(result.region, 'New South Wales');
      expect(result.city, 'Sydney');
      expect(result.isp, 'Google LLC');
      expect(result.latitude?.toStringAsFixed(6), '-33.867779');
      expect(result.longitude?.toStringAsFixed(6), '151.207047');
      expect(result.domain, 'google.com');
      expect(result.zipCode, '2000');
      expect(result.netSpeed, 'T1');
      expect(result.timeZone, '+11:00');
      expect(result.iddCode, '61');
      expect(result.areaCode, '02');
      expect(result.weatherStationCode, 'ASXX0112');
      expect(result.weatherStationName, 'Sydney');
      expect(result.mcc, '-');
      expect(result.mnc, '-');
      expect(result.mobileBrand, '-');
      expect(result.elevation, 1.0);
      expect(result.usageType, 'DCH');
      expect(result.addressType, 'U');
      expect(result.category, 'IAB19-11');
      expect(result.district, '-');
      expect(result.asn, '15169');
      expect(result.asName, 'Google LLC');
    });
    test('Normal IPv6 DE', () async {
      var ipl = IP2Location(databasePath: db26IPv6File);
      var result = await ipl.getAll('2a03:b0c0:3:d0::101:4001');
      expect(result.ipAddress, '2A03:B0C0:0003:00D0:0000:0000:0101:4001');
      expect(result.countryShort, 'DE');
      expect(result.countryLong, 'Germany');
      expect(result.region, 'Hessen');
      expect(result.city, 'Frankfurt am Main');
      expect(result.isp, 'ServerStack Inc.');
      expect(result.latitude?.toStringAsFixed(6), '50.110882');
      expect(result.longitude?.toStringAsFixed(6), '8.681996');
      expect(result.domain, 'serverstack.com');
      expect(result.zipCode, '65931');
      expect(result.netSpeed, 'T1');
      expect(result.timeZone, '+02:00');
      expect(result.iddCode, '49');
      expect(result.areaCode, '069');
      expect(result.weatherStationCode, 'GMXX0040');
      expect(result.weatherStationName, 'Frankfurt/Main');
      expect(result.mcc, '-');
      expect(result.mnc, '-');
      expect(result.mobileBrand, '-');
      expect(result.elevation, 112.0);
      expect(result.usageType, 'DCH');
      expect(result.addressType, 'U');
      expect(result.category, 'IAB19');
      expect(result.district, 'Regierungsbezirk Darmstadt');
      expect(result.asn, '14061');
      expect(result.asName, 'DigitalOcean LLC');
    });
  }, skip: 'Skipping Normal IPv6 tests first.');
  group('Test IPv4-Mapped IPv6', () {
    test('IPv4-Mapped IPv6 ZA', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('::ffff:197.85.191.64');
      expect(result.ipAddress, '0000:0000:0000:0000:0000:FFFF:197.85.191.64');
      expect(result.countryShort, 'ZA');
      expect(result.countryLong, 'South Africa');
      expect(result.region, 'Western Cape');
      expect(result.city, 'Cape Town');
      expect(result.isp, 'Dimension Data');
      expect(result.latitude?.toStringAsFixed(6), '-33.925552');
      expect(result.longitude?.toStringAsFixed(6), '18.422857');
      expect(result.domain, 'dimensiondata.com');
      expect(result.zipCode, '8160');
      expect(result.netSpeed, 'T1');
      expect(result.timeZone, '+02:00');
      expect(result.iddCode, '27');
      expect(result.areaCode, '021');
      expect(result.weatherStationCode, 'SFXX0010');
      expect(result.weatherStationName, 'Cape Town');
      expect(result.mcc, '-');
      expect(result.mnc, '-');
      expect(result.mobileBrand, '-');
      expect(result.elevation, 24.0);
      expect(result.usageType, 'DCH');
      expect(result.addressType, 'U');
      expect(result.category, 'IAB19');
      expect(result.district, 'City of Cape Town');
      expect(result.asn, '10474');
      expect(result.asName, 'African Network Information Center');
    });
    test('IPv4-Mapped IPv6 US', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('::FFFF:64.94.62.0');
      expect(result.ipAddress, '0000:0000:0000:0000:0000:FFFF:64.94.62.0');
      expect(result.countryShort, 'US');
      expect(result.countryLong, 'United States of America');
      expect(result.region, 'Florida');
      expect(result.city, 'Hialeah');
      expect(result.isp, 'zipdata.net');
      expect(result.latitude?.toStringAsFixed(6), '25.942320');
      expect(result.longitude?.toStringAsFixed(6), '-80.390404');
      expect(result.domain, 'zipdata.net');
      expect(result.zipCode, '33018');
      expect(result.netSpeed, 'T1');
      expect(result.timeZone, '-04:00');
      expect(result.iddCode, '1');
      expect(result.areaCode, '305');
      expect(result.weatherStationCode, 'USFL0196');
      expect(result.weatherStationName, 'Hialeah');
      expect(result.mcc, '-');
      expect(result.mnc, '-');
      expect(result.mobileBrand, '-');
      expect(result.elevation, 1.0);
      expect(result.usageType, 'DCH');
      expect(result.addressType, 'U');
      expect(result.category, 'IAB19-11');
      expect(result.district, 'Miami-Dade County');
      expect(result.asn, '395951');
      expect(result.asName, 'zipdata.net');
    });
  }, skip: 'Skipping IPv4-mapped IPv6 tests first.');
  group('Test Teredo', () {
    test('Teredo Yahoo', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('2001:0000:4136:e378:8000:63bf:f7fc:ddff');
      expect(result.ipAddress, '2001:0000:4136:E378:8000:63BF:F7FC:DDFF');
      expect(result.countryShort, 'US');
      expect(result.countryLong, 'United States of America');
      expect(result.region, 'California');
      expect(result.city, 'Sunnyvale');
      expect(result.isp, 'Yahoo! Inc.');
      expect(result.latitude?.toStringAsFixed(6), '37.401245');
      expect(result.longitude?.toStringAsFixed(6), '-122.007523');
      expect(result.domain, 'yahoo.com');
      expect(result.zipCode, '94089');
      expect(result.netSpeed, 'T1');
      expect(result.timeZone, '-07:00');
      expect(result.iddCode, '1');
      expect(result.areaCode, '408/650');
      expect(result.weatherStationCode, 'USCA1116');
      expect(result.weatherStationName, 'Sunnyvale');
      expect(result.mcc, '-');
      expect(result.mnc, '-');
      expect(result.mobileBrand, '-');
      expect(result.elevation, 38.0);
      expect(result.usageType, 'SES');
      expect(result.addressType, 'U');
      expect(result.category, 'IAB19-11');
      expect(result.district, 'Santa Clara County');
      expect(result.asn, '3356');
      expect(result.asName, 'Level 3 Parent LLC');
    });
    test('Teredo Google', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('2001:0:4136:e378:8000:63bf:f7f7:f7f7');
      expect(result.ipAddress, '2001:0:4136:E378:8000:63BF:F7F7:F7F7');
      expect(result.countryShort, 'US');
      expect(result.countryLong, 'United States of America');
      expect(result.region, 'California');
      expect(result.city, 'Mountain View');
      expect(result.isp, 'Google LLC');
      expect(result.latitude?.toStringAsFixed(6), '37.405991');
      expect(result.longitude?.toStringAsFixed(6), '-122.078514');
      expect(result.domain, 'google.com');
      expect(result.zipCode, '94043');
      expect(result.netSpeed, 'T1');
      expect(result.timeZone, '-07:00');
      expect(result.iddCode, '1');
      expect(result.areaCode, '650');
      expect(result.weatherStationCode, 'USCA0746');
      expect(result.weatherStationName, 'Mountain View');
      expect(result.mcc, '-');
      expect(result.mnc, '-');
      expect(result.mobileBrand, '-');
      expect(result.elevation, 32.0);
      expect(result.usageType, 'DCH');
      expect(result.addressType, 'A');
      expect(result.category, 'IAB19-11');
      expect(result.district, 'San Diego County');
      expect(result.asn, '15169');
      expect(result.asName, 'Google LLC');
    });
  }, skip: 'Skipping Teredo tests first.');
  group('Test 6to4', () {
    test('6to4 Yahoo', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('2002:0803:2200::0803:2200');
      expect(result.ipAddress, '2002:0803:2200::0803:2200');
      expect(result.countryShort, 'US');
      expect(result.countryLong, 'United States of America');
      expect(result.region, 'California');
      expect(result.city, 'Sunnyvale');
      expect(result.isp, 'Yahoo! Inc.');
      expect(result.latitude?.toStringAsFixed(6), '37.401245');
      expect(result.longitude?.toStringAsFixed(6), '-122.007523');
      expect(result.domain, 'yahoo.com');
      expect(result.zipCode, '94089');
      expect(result.netSpeed, 'T1');
      expect(result.timeZone, '-07:00');
      expect(result.iddCode, '1');
      expect(result.areaCode, '408/650');
      expect(result.weatherStationCode, 'USCA1116');
      expect(result.weatherStationName, 'Sunnyvale');
      expect(result.mcc, '-');
      expect(result.mnc, '-');
      expect(result.mobileBrand, '-');
      expect(result.elevation, 38.0);
      expect(result.usageType, 'SES');
      expect(result.addressType, 'U');
      expect(result.category, 'IAB19-11');
      expect(result.district, 'Santa Clara County');
      expect(result.asn, '3356');
      expect(result.asName, 'Level 3 Parent LLC');
    });
    test('6to4 Google', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('2002:808:808::');
      expect(result.ipAddress, '2002:808:808::');
      expect(result.countryShort, 'US');
      expect(result.countryLong, 'United States of America');
      expect(result.region, 'California');
      expect(result.city, 'Mountain View');
      expect(result.isp, 'Google LLC');
      expect(result.latitude?.toStringAsFixed(6), '37.405991');
      expect(result.longitude?.toStringAsFixed(6), '-122.078514');
      expect(result.domain, 'google.com');
      expect(result.zipCode, '94043');
      expect(result.netSpeed, 'T1');
      expect(result.timeZone, '-07:00');
      expect(result.iddCode, '1');
      expect(result.areaCode, '650');
      expect(result.weatherStationCode, 'USCA0746');
      expect(result.weatherStationName, 'Mountain View');
      expect(result.mcc, '-');
      expect(result.mnc, '-');
      expect(result.mobileBrand, '-');
      expect(result.elevation, 32.0);
      expect(result.usageType, 'DCH');
      expect(result.addressType, 'A');
      expect(result.category, 'IAB19-11');
      expect(result.district, 'San Diego County');
      expect(result.asn, '15169');
      expect(result.asName, 'Google LLC');
    });
  }, skip: 'Skipping 6to4 tests first.');
  group('Test Invalid IP', () {
    test('Test Invalid 1', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('0.0.0.256');
      expect(result.ipAddress, '0.0.0.256');
      expect(result.countryShort, null);
      expect(result.countryLong, null);
      expect(result.region, null);
      expect(result.city, null);
      expect(result.isp, null);
      expect(result.latitude?.toStringAsFixed(6), null);
      expect(result.longitude?.toStringAsFixed(6), null);
      expect(result.domain, null);
      expect(result.zipCode, null);
      expect(result.netSpeed, null);
      expect(result.timeZone, null);
      expect(result.iddCode, null);
      expect(result.areaCode, null);
      expect(result.weatherStationCode, null);
      expect(result.weatherStationName, null);
      expect(result.mcc, null);
      expect(result.mnc, null);
      expect(result.mobileBrand, null);
      expect(result.elevation, null);
      expect(result.usageType, null);
      expect(result.addressType, null);
      expect(result.category, null);
      expect(result.district, null);
      expect(result.asn, null);
      expect(result.asName, null);
    });
    test('Test Invalid 2', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('0.0.0');
      expect(result.ipAddress, '0.0.0');
      expect(result.countryShort, null);
      expect(result.countryLong, null);
      expect(result.region, null);
      expect(result.city, null);
      expect(result.isp, null);
      expect(result.latitude?.toStringAsFixed(6), null);
      expect(result.longitude?.toStringAsFixed(6), null);
      expect(result.domain, null);
      expect(result.zipCode, null);
      expect(result.netSpeed, null);
      expect(result.timeZone, null);
      expect(result.iddCode, null);
      expect(result.areaCode, null);
      expect(result.weatherStationCode, null);
      expect(result.weatherStationName, null);
      expect(result.mcc, null);
      expect(result.mnc, null);
      expect(result.mobileBrand, null);
      expect(result.elevation, null);
      expect(result.usageType, null);
      expect(result.addressType, null);
      expect(result.category, null);
      expect(result.district, null);
      expect(result.asn, null);
      expect(result.asName, null);
    });
    test('Test Invalid 3', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('1');
      expect(result.ipAddress, '1');
      expect(result.countryShort, null);
      expect(result.countryLong, null);
      expect(result.region, null);
      expect(result.city, null);
      expect(result.isp, null);
      expect(result.latitude?.toStringAsFixed(6), null);
      expect(result.longitude?.toStringAsFixed(6), null);
      expect(result.domain, null);
      expect(result.zipCode, null);
      expect(result.netSpeed, null);
      expect(result.timeZone, null);
      expect(result.iddCode, null);
      expect(result.areaCode, null);
      expect(result.weatherStationCode, null);
      expect(result.weatherStationName, null);
      expect(result.mcc, null);
      expect(result.mnc, null);
      expect(result.mobileBrand, null);
      expect(result.elevation, null);
      expect(result.usageType, null);
      expect(result.addressType, null);
      expect(result.category, null);
      expect(result.district, null);
      expect(result.asn, null);
      expect(result.asName, null);
    });
    test('Test Invalid 4', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAll('A');
      expect(result.ipAddress, 'A');
      expect(result.countryShort, null);
      expect(result.countryLong, null);
      expect(result.region, null);
      expect(result.city, null);
      expect(result.isp, null);
      expect(result.latitude?.toStringAsFixed(6), null);
      expect(result.longitude?.toStringAsFixed(6), null);
      expect(result.domain, null);
      expect(result.zipCode, null);
      expect(result.netSpeed, null);
      expect(result.timeZone, null);
      expect(result.iddCode, null);
      expect(result.areaCode, null);
      expect(result.weatherStationCode, null);
      expect(result.weatherStationName, null);
      expect(result.mcc, null);
      expect(result.mnc, null);
      expect(result.mobileBrand, null);
      expect(result.elevation, null);
      expect(result.usageType, null);
      expect(result.addressType, null);
      expect(result.category, null);
      expect(result.district, null);
      expect(result.asn, null);
      expect(result.asName, null);
    });
  }, skip: 'Skipping Invalid IP tests first.');
  group('Test Individual Fields', () {
    test('Test Country Short', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getCountryShort('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, 'US');
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Country Long', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getCountryLong('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, 'United States of America');
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Region', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getRegion('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, 'California');
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test City', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getCity('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, 'Mountain View');
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test ISP', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getIsp('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, 'Google LLC');
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Latitude', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getLatitude('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '37.405991');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Longitude', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getLongitude('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '-122.078514');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Domain', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getDomain('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, 'google.com');
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test ZIP Code', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getZipCode('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, '94043');
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Net Speed', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getNetSpeed('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, 'T1');
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Time Zone', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getTimeZone('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, '-07:00');
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test IDD Code', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getIddCode('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, '1');
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Area Code', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAreaCode('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, '650');
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Weather Station Code', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getWeatherStationCode('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, 'USCA0746');
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Weather Station Name', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getWeatherStationName('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, 'Mountain View');
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test MCC', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getMcc('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, '-');
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test MNC', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getMnc('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, '-');
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Mobile Brand', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getMobileBrand('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, '-');
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Elevation', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getElevation('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 32.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Usage Type', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getUsageType('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, 'DCH');
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Address Type', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAddressType('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, 'A');
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test Category', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getCategory('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, 'IAB19-11');
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test District', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getDistrict('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, 'San Diego County');
      expect(result.asn, notSupported);
      expect(result.asName, notSupported);
    });
    test('Test ASN', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAsn('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, '15169');
      expect(result.asName, notSupported);
    });
    test('Test AS Name', () async {
      var ipl = IP2Location(databasePath: db26IPv4File);
      var result = await ipl.getAsName('8.8.8.8');
      expect(result.ipAddress, '8.8.8.8');
      expect(result.countryShort, notSupported);
      expect(result.countryLong, notSupported);
      expect(result.region, notSupported);
      expect(result.city, notSupported);
      expect(result.isp, notSupported);
      expect(result.latitude?.toStringAsFixed(6), '0.000000');
      expect(result.longitude?.toStringAsFixed(6), '0.000000');
      expect(result.domain, notSupported);
      expect(result.zipCode, notSupported);
      expect(result.netSpeed, notSupported);
      expect(result.timeZone, notSupported);
      expect(result.iddCode, notSupported);
      expect(result.areaCode, notSupported);
      expect(result.weatherStationCode, notSupported);
      expect(result.weatherStationName, notSupported);
      expect(result.mcc, notSupported);
      expect(result.mnc, notSupported);
      expect(result.mobileBrand, notSupported);
      expect(result.elevation, 0.0);
      expect(result.usageType, notSupported);
      expect(result.addressType, notSupported);
      expect(result.category, notSupported);
      expect(result.district, notSupported);
      expect(result.asn, notSupported);
      expect(result.asName, 'Google LLC');
    });
  }, skip: 'Skipping Individual Field tests first.');
}
